# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonar-demo'
    organization: 'pradeepcv'
    scannerMode: 'Other'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.projectKey=pradeepcv_Demonstration
      sonar.projectName=Demonstration
- task: Maven@4
  inputs:
    mavenPomFile: 'springcreditcard/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    sqMavenPluginVersionChoice: 'latest'

- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    command: 'login'
- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    repository: 'pradeepvenk99 / bootcamp'
    command: 'buildAndPush'
    Dockerfile: 'springcreditcard/Dockerfile'
- task: Docker@2
  inputs:
    containerRegistry: 'docker'
    command: 'logout'